Models/KantanjiModel/CAPDO.cs
namespace DOAN_WEB.Models.KantanjiModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("CAPDO")]
    public partial class CAPDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAPDO()
        {
            NGUCANHs = new HashSet<NGUCANH>();
        }

        [Key]
        public int IDCAPDO { get; set; }

        [Required]
        [StringLength(150)]
        public string TENCAPDO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUCANH> NGUCANHs { get; set; }
    }
}

Models/KantanjiModel/DEDOC.cs
namespace DOAN_WEB.Models.KantanjiModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DEDOC")]
    public partial class DEDOC
    {
        [Key]
        public int IDDOC { get; set; }

        public int IDBODE { get; set; }

        public int IDDH { get; set; }

        [Required]
        [StringLength(255)]
        public string CAUHOI { get; set; }

        [Required]
        [StringLength(255)]
        public string DA1 { get; set; }

        [Required]
        [StringLength(255)]
        public string DA2 { get; set; }

        [Required]
        [StringLength(255)]
        public string DA3 { get; set; }

        public virtual BODE BODE { get; set; }

        public virtual DOCHIEU DOCHIEU { get; set; }
    }
}

Models/KantanjiModel/DENGHE.cs
namespace DOAN_WEB.Models.KantanjiModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DENGHE")]
    public partial class DENGHE
    {
        [Key]
        public int IDNGHE { get; set; }

        public int IDAUDIO { get; set; }

        public int IDBODE { get; set; }

        [Required]
        [StringLength(255)]
        public string DA1 { get; set; }

        [Required]
        [StringLength(255)]
        public string DA2 { get; set; }

        [Required]
        [StringLength(255)]
        public string DA3 { get; set; }

        public virtual AUDIO AUDIO { get; set; }

        public virtual BODE BODE { get; set; }
    }
}

Models/KantanjiModel/FLASHCARD.cs
namespace DOAN_WEB.Models.KantanjiModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("FLASHCARD")]
    public partial class FLASHCARD
    {
        [Key]
        public int IDFC { get; set; }

        [Required]
        [StringLength(100)]
        public string MATTRUOC { get; set; }

        [Required]
        [StringLength(100)]
        public string MATSAU { get; set; }

        public int IDCHUDE { get; set; }

        public virtual CHUDECHINH CHUDECHINH { get; set; }
    }
}

Models/KantanjiModel/NGUCANH.cs
namespace DOAN_WEB.Models.KantanjiModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("NGUCANH")]
    public partial class NGUCANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUCANH()
        {
            KANJIs = new HashSet<KANJI>();
        }

        [Key]
        public int IDNGUCANH { get; set; }

        [Required]
        [StringLength(150)]
        public string TENNGUCANH { get; set; }

        [Required]
        [StringLength(150)]
        public string LINKANH { get; set; }

        public int IDCHUDE { get; set; }

        public int IDCAPDO { get; set; }

        public virtual CAPDO CAPDO { get; set; }

        public virtual CHUDECHINH CHUDECHINH { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KANJI> KANJIs { get; set; }
    }
}

Controllers/HomeController.cs
using DOAN_WEB.Models.KantanjiModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace DOAN_WEB.Controllers
{
    public class HomeController : Controller
    {
        // GET: kantanji
        KantanjiContext kantanjiDb = new KantanjiContext();
        //Bam Mat Khau
        //Mã hóa Password
        public static string EncodePassword(string originalPassword)
        {

            MD5 md5 = new MD5CryptoServiceProvider();
            // Compute hash from the bytes of text
            md5.ComputeHash(ASCIIEncoding.ASCII.GetBytes(originalPassword));
            // Get hash result after compute it
            byte[] result = md5.Hash;
            StringBuilder strBuilder = new StringBuilder();
            for (int i = 0; i < result.Length; i++)
            {
                strBuilder.Append(result[i].ToString("x2"));
            }

            return strBuilder.ToString();
        }


        public ActionResult Index()
        {
            return View();
        }

        //-------------------List Account--------------
        public ActionResult ListAccount()
        {
            List<USER> listUser = kantanjiDb.USERs.ToList();
            return View(listUser);
        }

        //-------------------Create Account--------------
        public ActionResult CreateAccount()
        {
            return View();
        }

        //THEM USERACCOUNT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAccount(USER obj)
        {
            string tam = obj.ENPASSWORD;
            obj.ENPASSWORD = EncodePassword(EncodePassword(tam));

            ModelState.Remove("Id");
            if (!ModelState.IsValid)
            {
                return View("Create", obj);
            }
            kantanjiDb.USERs.Add(obj);
            kantanjiDb.SaveChanges();

            return RedirectToAction("ListAccount", "Home");
        }


        //-------------------Edit Account--------------
        public ActionResult Edit(int id)
        {
           
            USER user = kantanjiDb.USERs.FirstOrDefault(p => p.IDUSER == id);

            return View(user);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( USER objuser)
        {
            string tam = objuser.ENPASSWORD;
            objuser.ENPASSWORD = EncodePassword(EncodePassword(tam));
            if (ModelState.IsValid)
            {
                kantanjiDb.Entry(objuser).State = EntityState.Modified;
                kantanjiDb.SaveChanges();
                return RedirectToAction("ListAccount", "Home");

            }

            return View(objuser);
        }
        //-------------------Delete Account--------------
        public ActionResult Delete(int id)
        {
            
            USER user = kantanjiDb.USERs.FirstOrDefault(p => p.IDUSER == id);
            if (user == null)
            {
                return HttpNotFound();
            }


            return View(user);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            USER user = kantanjiDb.USERs.FirstOrDefault(p => p.IDUSER == id);
            kantanjiDb.USERs.Remove(user);
            kantanjiDb.SaveChanges();
            return RedirectToAction("ListAccount", "Home");


        }
        //-------------------Account Details--------------
        public ActionResult Details(int id)
        {

            USER user = kantanjiDb.USERs.FirstOrDefault(p => p.IDUSER == id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

    }
}

Controllers/kantanjiController.cs
using DOAN_WEB.Models.KantanjiModel;
using DOAN_WEB.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DOAN_WEB.Controllers
{
    public class kantanjiController : Controller
    {
        // GET: kantanji
        KantanjiContext kantanjiDb = new KantanjiContext();
       
        //--------------------HOME------------------
        public ActionResult Home()
        {
            return View();
        }

        //---------------------CHU DE-----------------
        public ActionResult Cap_Do()
        {
            List<CAPDO> listCD = kantanjiDb.CAPDOes.ToList();
            return PartialView(listCD);
        }

        public ActionResult ChuDe()
        {
            List<CHUDECHINH> listCD = kantanjiDb.CHUDECHINHs.ToList();
            return View(listCD);
        }

        public ActionResult NguCanh(int idcapdo)
        {
            List<NGUCANH> listNC = kantanjiDb.NGUCANHs.Where(a => a.IDCAPDO == idcapdo ).ToList();
            string tenCAPDO = kantanjiDb.CAPDOes.Where(a => a.IDCAPDO == idcapdo).Single().TENCAPDO.ToString();
            ViewBag.TenCAPDO = tenCAPDO;
            return View(listNC);
        }

        public ActionResult ListKJ()
        {
            List<KANJI> listkanji = kantanjiDb.KANJIs.ToList();
            return View(listkanji);
        }

        public ActionResult ChitietKJ(int id)
        {
            KANJI kanji = kantanjiDb.KANJIs.SingleOrDefault(n => n.IDKANJI == id);

            return View(kanji);
        }

        //--------------LUYEN TAP-------------------
        public ActionResult LuyenTap()
        {
            List<CHUDECHINH> listCD = kantanjiDb.CHUDECHINHs.ToList();
            return View(listCD);
        }
        public ActionResult Trochoi()
        {
          
            return View();
        }
        public ActionResult Trochoi2()
        {

            return View();
        }

        //-------------------FLASHCARD--------------
        public ActionResult MenuChuyenNganh()
        {
            List<CHUDECHINH> listCD = kantanjiDb.CHUDECHINHs.ToList();
            return PartialView(listCD);
        }

        public ActionResult FlashCard(int id)
        {
            List<FLASHCARD> listFC = kantanjiDb.FLASHCARDs.Where(a => a.IDCHUDE == id).ToList();
            string tenCN = kantanjiDb.CHUDECHINHs.Where(a => a.IDCHUDE == id).Single().TENCHUDE.ToString();
            ViewBag.TenCN = tenCN;
            return View(listFC);
        }

        public ActionResult FAQ()
        {
            return View();
        }
    
        //------------------THI NGAY----------------
        public ActionResult Cautruc()
        {       
            return View();
        }
        public ActionResult XacMinh()
        {
            //danh sách giảng viên được theo dõi bởi người dùng (đăng nhập) hiện tại
            /*var listFollwee = kantanjiDb..Where(p => p.FollowerId ==
            currentUser.Id).ToList();*/
            Account data = TempData["mydata"] as Account;
            THONGTIN tam = kantanjiDb.THONGTINs.SingleOrDefault(p=> p.IDUSER==data.AccountId);
            return PartialView(tam);
        }
        public ActionResult BaiThiTV()
        {
            List<DETVNP> listTV = kantanjiDb.DETVNPs.ToList();
            return View(listTV);
        }

        public ActionResult DeDoc()
        {
            List<DOCHIEU> listDD = kantanjiDb.DOCHIEUx.ToList();
            return PartialView(listDD);
        }

        public ActionResult BaiThiDocHieu()
        {
            List<DEDOC> listDH = kantanjiDb.DEDOCs.ToList();
            return View(listDH);
        }
        public ActionResult DeNghe()
        {
            List<AUDIO> listDN = kantanjiDb.AUDIOs.ToList();
            return PartialView(listDN);
        }

        public ActionResult BaiThiNghe()
        {
            List<DENGHE> lisTNH = kantanjiDb.DENGHEs.ToList();
            return View(lisTNH);
        }
        public ActionResult Camera()
        {
            return View();
        }
        public ActionResult HoanThanh()
        {
            return View();
        }
    }
}

Views/kantanji/BaiThiTV.cshtml
@model  List<DOAN_WEB.Models.KantanjiModel.DETVNP>
@{
    ViewBag.Title = "BaiThiTV";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <link href="~/Content/Style.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://codetienich.github.io/dulieu/quiz1.css">
    <link rel="stylesheet" href="https://codetienich.github.io/dulieu/quiz2.css">
    <script src="https://codetienich.github.io/dulieu/mainquiz1.js" type="text/javascript"></script>
</head>
<body>

    


    <div class="quiz-main" data-quiztype="Graded" data-duration="0">
        <ul>


            @foreach (var item in Model)
            {
                <li data-sectionid="@item.IDTVNP" class="quiz-section">
                    <div class="quiz-section-title">
                        <b><span style="color: black; font-family: Times, Times New Roman, serif;">Câu @item.IDTVNP: </span></b>
                        <b><span style="color: blue; font-family: Times, Times New Roman, serif;"> @item.CAUHOI</span></b>
                    </div>
                    <div class="quiz-section-content">
                        <div class="item item-question item-choices">
                            <ul class="list btn-group group-theme">
                                <li class="list-item">
                                    <label class="overlabel"><input type="radio" class="hide" name="option-@item.IDTVNP" /> <span class="mark"></span></label>
                                    <div class="boxcheck">
                                        <div class="answer-desc textview"> @item.DA1 </div>
                                    </div>
                                </li>
                                <li class="list-item">
                                    <label class="overlabel"><input type="radio" class="hide" name="option-@item.IDTVNP" /> <span class="mark"></span></label>
                                    <div class="boxcheck">
                                        <div class="answer-desc textview"> @item.DA2 </div>
                                    </div>
                                </li>
                                <li class="list-item">
                                    <label class="overlabel"><input type="radio" class="hide" name="option-@item.IDTVNP" /> <span class="mark"></span> </label>
                                    <div class="boxcheck">
                                        <div class="answer-desc textview"> @item.DA3 </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </li>
                <br />
            }

            <div class="quiz-check">
                <div class="quiz-result hide">
                </div>
            </div>
            <a href="@Url.Action("BaiThiDocHieu", "kantanji")">Tiếp tục </a>

    </div>
    </ul>

    </div>
</body>

</html>

Views/kantanji/Cap_Do.cshtml
@model List<DOAN_WEB.Models.KantanjiModel.CAPDO>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="~/Content/KantanjiStyle/kanjichudeST.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>
    @foreach (var item in Model)
    {
        <a href="@Url.Action("NguCanh", "kantanji", new {idcapdo=item.IDCAPDO})">@item.TENCAPDO</a>
    }
</body>
</html>

Views/kantanji/ChuDe.cshtml
@model  List<DOAN_WEB.Models.KantanjiModel.CHUDECHINH>
@{
    ViewBag.Title = "ChuDe";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="~/Content/KantanjiStyle/kanjichudeST.css" rel="stylesheet" />
</head>
<body>
    <div style="margin-top:35px;">
        @foreach (var item in Model)
        {
            <div class=" topic">

                <div class="anh">
                    <a href="#" class="anh_CD"><img src="~/Content/img/CD/@item.LINKANH"></a>
                </div>

                <div class="menu_CD">
                    <div class="ten_CD">
                        <h1>@item.TENCHUDE</h1>
                    </div>

                    <div class="text_lv">
                        <hr />
                        <h3>レべル</h3>
                    </div>
                    <div class="menu_lv">
                        @Html.Action("Cap_Do", "kantanji", new {item.IDCHUDE})
                    </div>
                </div>
            </div>
        }
    </div>

</body>
</html>

Views/kantanji/DeDoc.cshtml
@model  List<DOAN_WEB.Models.KantanjiModel.DOCHIEU>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>


    <div class="aside" style="margin-top:35px;"
        <ul class="major">
            @foreach (var item in Model)
            {
                <img src="~/Content/img/DH/@item.LINKANH"/>
            }

        </ul>

    </div>
</body>
</html>

Views/kantanji/FlashCard.cshtml
@model  List<DOAN_WEB.Models.KantanjiModel.FLASHCARD>
@{
    ViewBag.Title = "FlashCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/Content/KantanjiStyle/FlashCardStyle.css" rel="stylesheet" />
    <link href="~/Content/KantanjiStyle/FlippingFCStyle.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
        <div class="wrapper">
            <div class="container">
                <div class="content">
                    @Html.Action("MenuChuyenNganh", "kantanji")

                    <div class="main">
                        @*  *@
                        <h2 style="color: #07575B" class="title">@ViewBag.TenCN</h2>
                        <div class="main-content">
                            <div class="sentence">
                                <p style="color:#07575B">=> Số câu:1/10</p>
                                <h4 class="correct" style="cursor:pointer">Số câu đúng: 0</h4>
                                <h4 class="incorrect" style="cursor:pointer">Số câu sai: 0</h4>

                            </div>
                            <div class="flass-cards">
                                <div class="flass-card">

                                    @foreach (var item in Model)
                                    {
                                        <div class="flass-card-item">

                                            <div class="main_card">
                                                <div class="card">
                                                    <div class="card--front">
                                                        <h2>
                                                            @item.MATTRUOC
                                                        </h2>

                                                    </div>
                                                    <div class="card--back">
                                                        <h3>
                                                            @item.MATSAU
                                                        </h3>
                                                    </div>
                                                </div>
                                            </div>
                                            <i class="fa fa-volume-up sound" aria-hidden="true"></i>
                                            <audio src="m2.mp3" id="song"></audio>
                                        </div>
                                    }

                                    @*Flash Card chúc mừng*@
                                    <div class="flass-card-item">

                                        <div class="main_card">
                                            <div class="card">
                                                <div class="card--front">
                                                    <h2>
                                                        KẾT THÚC!
                                                    </h2>

                                                </div>
                                                <div class="card--back">
                                                    <h3>
                                                        Chúc mừng bạn đã hoàn thành
                                                    </h3>
                                                </div>
                                            </div>
                                        </div>
                                        <i class="fa fa-volume-up sound" aria-hidden="true"></i>
                                        <audio src="m2.mp3" id="song"></audio>
                                    </div>

                                </div>
                            </div>
                            <div class="slider-next"><i class="fa fa-angle-right "></i></div>

                        </div>

                    </div>
                </div>
            </div>

        </div>
        <script src="~/Scripts/KantanjiJS/flashCardScripts.js"></script>
    </body>
</html>

Views/kantanji/MenuChuyenNganh.cshtml
@model  List<DOAN_WEB.Models.KantanjiModel.CHUDECHINH>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="~/Content/KantanjiStyle/FlashCardStyle.css" rel="stylesheet" />
    <link href="~/Content/KantanjiStyle/FlippingFCStyle.css" rel="stylesheet" />
  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
   
</head>
<body>
        <div class="aside">
            <ul class="major">
                @foreach (var item in Model)
                {
                    <li><a style="background: #006e7b; width: 150px; margin: 8px;cursor: pointer; color: white; border-radius: 13px;font-size:9px;transition: 0.2s ease-in;text-align: center;text-decoration: none;" href="@Url.Action("FlashCard", "kantanji", new { id = item.IDCHUDE })" class="major-item">@item.TENCHUDE</a> </li>
                }

            </ul>
        </div>
    </body>
</html>

Views/kantanji/NguCanh.cshtml
@model  List<DOAN_WEB.Models.KantanjiModel.NGUCANH>
@{
    ViewBag.Title = "NguCanh";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="~/Content/KantanjiStyle/NguCanh.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body >
    <div class="NC_list">
        @foreach (var item in Model)
        {

            <div class="NC_link">

                <div class="ngucanh">

                    <a href="@Url.Action("ListKJ", "kantanji")" style="text-decoration:none">
                        <img src="~/Content/img/NguCanh/@item.LINKANH">
                        <p class="ngucanh_text" style=" color: black;">@item.TENNGUCANH</p>
                    </a>

                </div>

            </div>
        }
        <div class="NC_link">
            <div class="ngucanh">
                <a href="#" style="text-decoration:none">
                    <img src="~/Content/img/NguCanh/plus icon.png" alt="NhaHang">
                    <p class="ngucanh_text "  style=" color: black;">Thêm chủ đề</p>
                </a>
                
            </div>
            </div>
        </div>
</body>
</html>